name: recycle-mvp

services:
  # ---- Infra (MinIO) ----
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio123}
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # 콘솔
    volumes:
      - minio-data:/data
    networks: [ shared ]
    # profiles: [ infra ]   # 필요할 때만 켤 수 있게 프로파일 태깅

  # ---- App (API) ----
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - minio
    networks: [ shared ]
    # profiles: [ api ]      # 필요할 때만 켤 수 있게 프로파일 태깅

  # ---- App (추후에 추가) ----

networks:
  shared:

volumes:
  minio-data:
