name: Backend Test

on:
  pull_request:
    paths:
      - 'backend/**'           # ⭐ backend 디렉토리만
      - '.github/workflows/test.yml'  # workflow 자체 변경 시
  push:
    branches: [ main ]
    paths:
      - 'backend/**'           # ⭐ backend 디렉토리만
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build and test API
        run: |
          cd backend
          docker build --target test -t api-test -f apps/api/Dockerfile .
          docker run --rm api-test
      
      - name: Build and test Auth
        run: |
          cd backend
          docker build --target test -t auth-test -f apps/auth/Dockerfile .
          docker run --rm auth-test